app/urls.py
# from django.urls import path,include
# from .views import index


# app_name = 'app'

# urlpatterns = [
#     path('', index, name='index'),
#     path('products/', include('app.product_urls'))
# ]



# from django.urls import path, include
# from .views import index, detail


# app_name = 'app'  # ← this must match 'app' in 'app:index'

# urlpatterns = [
#     path('', index, name='index'),
#     path('category/<int:category_id>/', index, name='category'),
#     path('detail/<int:product_id>/', detail, name='detail'),
    
# ]


from django.urls import path,include
from .views import index,detail,create_product,delete_product,update_product,create_order,register

app_name = 'app'

urlpatterns = [
    path('',index,name='index'),
    path('category/<int:category_id>',index,name='products_of_category'),
    path('detail/<int:product_id>',detail,name='detail'),
    path('create/',create_product,name='create'),
    path('delete/<int:pk>',delete_product,name='delete'),
    path('update/<int:pk>',update_product,name='update'),
    path('detail/<int:pk>/orders/',create_order,name='create_order'),
    path('register/', register, name='register'),
]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app.urls',namespace='app')),
    path('user/',include('user.urls',namespace='user'))
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/templates/app/base/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>{%block title%} {%endblock%}</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'app/css/styles.css'  %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="{% url 'app:index'%}">Apelsin</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="#!">Home</a></li>
                        <li class="nav-item"><a class="nav-link" href="#!">About</a></li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Categories</a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="{% url 'app:index' %}">All Products</a></li>
                                <li><hr class="dropdown-divider" /></li>
                                {% for category in categories%}
                                    <li><a class="dropdown-item" href="{% url 'app:products_of_category' category.id %} ">{{category.title}}</a></li>
                                {%endfor%}
                            </ul>
                        </li>
                    </ul>
                    <form class="d-flex" action="{% url 'app:index' %}">
                        <input type="text" name="q" class="form-contro">
                        <button class="btn btn-outline-dark" type="submit">
                            <i class="bi-search-fill me-1"></i>
                            Search
                           
                        </button>
                    </form>
                </div>
            </div>
        </nav>
       
        {% block home_content%}
        {%endblock%}

        {%block detail_content%}
        {%endblock%}


        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2023</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'app/js/scripts.js' %}"></script>

    </body>
</html>